general.import = [
  # Uncomment the theme you want to use

  "~/.config/alacritty/catppuccin-mocha.toml", # catppuccin-mocha theme
  # "~/.config/alacritty/moonfly-default.toml", # moonfly theme
  # "~/.config/alacritty/gruvbox-dark-soft-contrast.toml",  # gruvbox theme
  # "~/.config/alacritty/cyberdream.toml", # cyberdream theme
  # "~/.config/alacritty/tokyo-night.toml", # tokyo-night theme (default)
  # "~/.config/alacritty/chicago95.toml", # chicago95 theme
  # "~/.config/alacritty/ayu_dark.toml", # ayu-dark theme
  # "~/.config/alacitty/aura.toml", # aura theme
]

[env]
TERM = "xterm-256color"
PYTHONWARNINGS = "ignore"
LANG = "en_US.UTF-8"

[cursor.style]
blinking = "On" # values are =['On', 'Off', 'Always','Never']
shape = "Block"

# dir
[font]
size = 14.00

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[terminal]
shell.program = "/usr/bin/zsh"

[bell]
animation = "EaseOutExpo"
duration = 150
color = "#cccccc"

[window]
decorations = "full"
dynamic_padding = true
# opacity = 0.75
# blur = true
startup_mode = "Windowed"
title = "Alacritty"

[window.padding]
x = 5
y = 5

# Keybindings
[keyboard]
bindings = [
  { key = "`", mods = "Control", action = "ToggleFullscreen" },
  { key = "q", mods = "Control", action = "Quit" },
  { key = "t", mods = "Control", action = "CreateNewTab" },
]
